### ISSUE TITLE
Analyze SDR math by Subutai & create classes to calculate important statistics

### ISSUE THREAD

**Issue by quinnliu** [WalnutiQ/WalnutiQ#152]
Slide show Presentation he gave [here](https://db.tt/XwkPhOlM)
Slide show by Subutai Video [here](https://www.youtube.com/watch?v=LbZtc_zWBS4)
1st draft of paper here behind SDRs [here](http://numenta.com/learn/properties-of-sparse-distributed-representations.html)

**Comment by quinnliu** [comment]
Link to draft about math behind SDRs: http://numenta.com/learn/properties-of-sparse-distributed-representations.html

**Comment by quinnliu** [comment]
Important to understand: When thinking about permutation and combinations the ORDER means selection over time. In the case of 1 SDR the selection is all at the same so ORDER does not matter.

**Comment by quinnliu** [comment]
- n = number of neurons
- w = number of active neurons
- n choose w = number of unique SDRs at each timestep of a Region with n neurons

**Comment by quinnliu** [comment]
- Let x be an SDR
- The overlap set of x with respect to b, overlap_x(n, w, b) is the set of vectors of size n with w bits
  ON, that have exactly b bits of overlap with x.

- overlap_x(n, w, b) = (w_x choose b) * ((n-w_x) choose (w-b)) where b <= w
- EXAMPLE: n = 1024, w = 40, b = 33
  + overlap_x(1024, 40, 33) = (40 choose 33) * (984 choose 7)
     - 40 choose 33 = 33 ON bits of overlap with SDR x(which also has 40 ON bits)
     - 984 choose 7 = 7 ON bits that do NOT overlap with SDR x(which also has 40 ON bits)

**Comment by quinnliu** [comment]
## False Positive

- Given 2 random SDRs x and y, what is the probability of a false match? The chance that overlap(x,
  y) >= theta?
- Probability of false match = (chances of match from b = theta to b = w) / total_possible_SDRs
- Probability of false match = Sum b = theat to b = w of overlap_x(n, w, b) / (n choose w)

**Comment by quinnliu** [comment]
## Subsampling
- possibly necessary for classification

**Comment by quinnliu** [comment]
## Classifying a Set of Vectors
- fuzzy on math... need to take deeper look

**Comment by quinnliu** [comment]
![drawing_1](https://cloud.githubusercontent.com/assets/2585159/6205369/85b13b72-b539-11e4-9c42-1a1b06c3ca78.jpg)

**Comment by quinnliu** [comment]
![drawing_2](https://cloud.githubusercontent.com/assets/2585159/6205377/c25b1bb0-b539-11e4-9ec8-6cf65256bdc1.jpg)

**Comment by quinnliu** [comment]
![image](https://cloud.githubusercontent.com/assets/2585159/6320615/7e5c4188-bab0-11e4-84b9-fb0eea530c81.png)

**Comment by quinnliu** [comment]
Overlap Set of a SDR called X = the set of SDRs (let's call them Y_1, Y_2, ...) with exactly n total neurons, w active neurons, and b neurons the match exactly with the original SDR.

**Comment by mjdeasy** [comment]
##More Variable Definitions
b = Range from theta to w that represents the number of neurons that do match between two given SDR's. 
false positive for SDR called X = The chance of SDR Y matching SDR X with noise bound but not representing the same image. (we want this to be small)  
noise = theta / w = The threshold of difference in number of active neurons allowed while still considering the image to be the same

**Comment by mjdeasy** [comment]
## More Variable Definitions
- b = Range from theta to w that represents the number of neurons that do match between two given SDR's. 
- False Positive for SDR called X = The chance of SDR Y matching SDR X with noise bound but not representing the same image. (we want this to be small)
- Noise = theta / w = The threshold of difference in number of active neurons allowed while still considering the image to be the same

**Comment by quinnliu** [comment]
![image](https://cloud.githubusercontent.com/assets/2585159/6320784/7ef1a228-bab5-11e4-8900-9aadb564e508.png)

**Comment by quinnliu** [comment]
Question: Why there are not false negatives (end of page 10).
Possible Answer: This math is for a 1 brain model with 1 training set and not 2 different brains with 2 different training sets.

**Comment by quinnliu** [comment]
## Probability of False Positive for SDR x Intersect SDR set M
probability = (1 - (1 - s)^SDRSetMSize)^w
- where:
  + s = Percentage of ON bits in all SDRs x and in M.
  + M = Set of SDRs joined with union property
  + w = Number of active "bits" in all SDRs.

**Comment by quinnliu** [comment]
# SDRs and HTM
### Where are the SDRs?

SDR is the primary data structure used in the cortex, and used everywhere in HTM systems. The algorithm as described in (Hawkins, 2010) is critically reliant on binary SDR's. In fact, there isn't a single unitary SDR. Instead there are a number of distinct SDRs used in specific ways. The following SDRs are involved in different parts of the CLA algorithm:
- cell proximal dendritic segments
- cell distal dendritic segments
- temporal predictions for T - 1
- active state in temporal memory
- pooled state

**Comment by quinnliu** [comment]
We first summarize the mathematical operations on SDR's in the CLA. We then discuss how to achieve robustness in each of the following operations:
- Spatial pooling and understanding column overlaps.
- Segment learning and the effects of noise in learning sequences.
- Capacity for high order temporal sequences.
- Capacity for making predictions.
- Temporal pooling and invariances.

**Comment by quinnliu** [comment]
This chapter assumes the reader is familiar with the basics of the CLA implementation and pseudocode in the whitepaper(Hawkins, 2010). Note that operations such as hierarchy, feedback, sensorimotor inference, and motor commands also use specific SDR's and rely on SDR properties.

### Notation
We use the phrase "temporal memory" to refer to the sequence learning portion of the pseudocode in Chapter 4 of the whitepaper. The following constants are used:
- N = size of input vector
- C = number of columns
- k = the number of columns active after spatial inhibition
- L = total number of cells
- S = number of segments per cell

**Comment by quinnliu** [comment]
Done implementing all mathematical error calculations so merging to master for now. In the future more math will be available for temporal memory part of algorithm.

**Comment by quinnliu** [comment]
Reopen when draft gets updated.
