### ISSUE TITLE
Fix IntelliJ Install Instructions on Mac

### ISSUE THREAD

**Issue by megdt923** [WalnutiQ/WalnutiQ#160]
Change to a better quote

**Comment by quinnliu** [comment]
Download Java 7 jdk here: http://www.oracle.com/technetwork/java/javase/downloads/jdk7-downloads-1880260.html

**Comment by megdt923** [comment]
## Install in Linux/Mac/Windows with IntelliJ
1. [Install IntelliJ IDEA FREE Community Edition](http://www.jetbrains.com/idea/download/).

2. Go to the top right of this page and hit the `Fork` button. Then clone your 
   forked WalnutiQ repository locally.  

3. Open up IntelliJ and click "Import Project" `=>` Select "Gradle" `=>` Next 
   `=>` Select "Use default gradle wrapper (recommended)" `=>` Finish

4. In IntelliJ right-click the `WalnutiQ/` folder and select "Run 'All Tests'".
