### ISSUE TITLE
Creating a large brain model story

### ISSUE THREAD

**Issue by quinnliu** [WalnutiQ/WalnutiQ#183]
# The Beginning of the Story
Me: I am really interested in building an object oriented model of how the human brain works. 

So I started this open source project @ [github.com/WalnutiQ/WalnutiQ](https://github.com/WalnutiQ/WalnutiQ)

**Comment by quinnliu** [comment]
# The Middle 

So I built my really large brain model:
![image](https://cloud.githubusercontent.com/assets/2585159/8238824/13a39da2-15c6-11e5-8d30-2b61115c469f.png)

<b>Problem:</b>

**Comment by quinnliu** [comment]
# More Middle

<b>Problem:</b>
```
Exception in thread "main" java.lang.OutOfMemoryError: GC overhead limit exceeded
```

**Comment by quinnliu** [comment]
![image](https://cloud.githubusercontent.com/assets/2585159/8239676/5d491ebe-15cb-11e5-8ad2-55e2c078f659.png)

**Comment by quinnliu** [comment]
![image](https://cloud.githubusercontent.com/assets/2585159/8239700/88e3d6fe-15cb-11e5-901a-fbd21cabd9aa.png)

**Comment by quinnliu** [comment]
![image](https://cloud.githubusercontent.com/assets/2585159/8239707/9708c3ac-15cb-11e5-9cf9-a7d75a1009ec.png)

**Comment by quinnliu** [comment]
![image](https://cloud.githubusercontent.com/assets/2585159/8239751/db009742-15cb-11e5-84d7-0c3fd2fe803d.png)

**Comment by quinnliu** [comment]
# End of Story
I was tired and very frustrated so I gave up.

**Comment by HunterSmith-1over12** [comment]
# Back to middle of the Story

No Q! You can't give up!

## Idea for not using so much Heap at once!

![image](https://cloud.githubusercontent.com/assets/12957037/8240050/f3470a82-15cd-11e5-8c61-b7164f25f02f.png)

Write the nodes that you don't need to disk at the moment to disk freeing up heap space.

**Comment by HunterSmith-1over12** [comment]
### Before
```java
NervousSystem nervousSystem = new NervousSystem(neocortex, null, retina);
```

### After

**Comment by HunterSmith-1over12** [comment]
Blue Circles = Very first time without writing unused nodes to disk & getting MEMORY ERROR
Red Circles = After writing unused noes to disk
![image](https://cloud.githubusercontent.com/assets/12957037/8240383/3742e5f6-15d0-11e5-8acd-083162e59976.png)

**Comment by HunterSmith-1over12** [comment]
# Plot Twist
I am also Q

**Comment by HunterSmith-1over12** [comment]
# Plot Twist
I am also Q.

# THE END

**Comment by HunterSmith-1over12** [comment]
# Plot Twist
Hunter Smith is also Q.

# THE END

**Comment by HunterSmith-1over12** [comment]
# Plot twist
Hunter Smith is Q.

# The End
